### ISSUE TITLE
`tests/misc/test_vm_basic_operations.py::Test::test_suspend` lacks prerequisite information

### ISSUE THREAD

**Issue by ydirson** [xcp-ng/xcp-ng-tests#244]
When running against my 8.3 test host I get a funky error blaming the VM, which likely rather points to some host misconfiguration, or is this a test error?

```
E           lib.commands.SSHCommandFailed: SSH command (xe vm-suspend uuid=874508ca-b340-096e-2523-808e3b37aec4) failed with return code 1: This VM does not have a suspend SR specified.
```

**Comment by benjamreis** [comment]
Hmm it means the pool has no default suspend SR configured or something like that.
It can happen when you install a host with no SR then add one after.

**Comment by ydirson** [comment]
that's `suspend-image-SR`, I document that in #242
